name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd degree-thesis/en
        make docker
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with: 
        name: PDF
        path: degree-thesis/en/pdf
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: |
          degree-thesis/en/main.aux 
          degree-thesis/en/main.bbl 
          degree-thesis/en/main.bcf 
          degree-thesis/en/main.blg 
          degree-thesis/en/main.log 
          degree-thesis/en/main.out 
          degree-thesis/en/main.run.xml 
          degree-thesis/en/main.toc
